version: '3'

services:
  vue-clicksign:
    container_name: vue-clicksign_dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 5173:5173
